# Creating Numpy Arry

In [4]:
import numpy as np

In [5]:
mylist=[1,2,3,4]

In [6]:
mylist

[1, 2, 3, 4]

In [8]:
type(mylist)

list

In [9]:
a=np.array(mylist)

In [10]:
a

array([1, 2, 3, 4])

In [11]:
type(a)

numpy.ndarray

In [12]:
my_Matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_Matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.matrix(my_Matrix)

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Built-in Methods of Numpy

# 1.arange()

In [16]:
np.arange(1,10,2) #arange(stat_index,end_index,step_Size)

array([1, 3, 5, 7, 9])

In [19]:
np.arange(2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

# 2.Zeroes and Ones

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.zeros(4)

array([0., 0., 0., 0.])

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones(4)

array([1., 1., 1., 1.])

In [32]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 3.Linspace

In [33]:
np.linspace(0,9,4) #Linspace having three parameters the are (start,end,time_interval)

array([0., 3., 6., 9.])

In [36]:
np.linspace(0,9,25)

array([0.   , 0.375, 0.75 , 1.125, 1.5  , 1.875, 2.25 , 2.625, 3.   ,
       3.375, 3.75 , 4.125, 4.5  , 4.875, 5.25 , 5.625, 6.   , 6.375,
       6.75 , 7.125, 7.5  , 7.875, 8.25 , 8.625, 9.   ])

In [37]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

# 4.Eye()

In [40]:
 np.eye(4)   #it returns the identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 5. Random()

## i.Rand

In [45]:
np.random.rand(4)   #Random Samples from uniform distribution over[0,1]

array([0.85557527, 0.19317959, 0.25887524, 0.23495613])

In [46]:
np.random.rand(5,5)

array([[0.16292454, 0.21782399, 0.25832435, 0.0486006 , 0.63532182],
       [0.09705082, 0.24072013, 0.87355687, 0.97402415, 0.72782996],
       [0.46194564, 0.58198841, 0.69762164, 0.04395737, 0.28178671],
       [0.1100676 , 0.27360519, 0.03247286, 0.18028063, 0.69934318],
       [0.72511797, 0.04926448, 0.8240387 , 0.74212731, 0.71850392]])

## ii.Randn

In [53]:
np.random.randn(2)   #return a samples from "Standerd Normal Distribution"

array([ 0.91728576, -0.28743985])

In [58]:
np.random.randn(5,5)

array([[ 0.07112394,  1.43403472, -0.14429141,  2.53721662, -0.52121135],
       [-0.04045793, -1.43911308, -0.22057064, -1.23984559,  0.90098723],
       [-0.24150259, -0.00604763, -0.99441199,  0.23019271, -0.3475001 ],
       [-0.67983933,  0.16462319,  0.08978908,  0.09655627, -0.2503596 ],
       [-0.39686423,  0.73166688, -1.47049021, -0.95420155,  0.18998466]])

# iii.Randint

In [69]:
np.random.randint(1,100)  #returns a random integer number

87

In [72]:
np.random.randint(1,100,10)

array([69, 57, 92, 96, 59, 92, 96, 53, 10, 29])

# 6.Reshape()

In [73]:
arr=np.arange(25)

In [76]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
arr.reshape(3,4)

ValueError: cannot reshape array of size 25 into shape (3,4)

In [78]:
arrr=np.random.randint(0,100,50)

In [79]:
arrr

array([18, 51, 66, 24, 52, 21, 95, 52, 13, 15, 34, 17, 36, 80, 43,  1, 38,
       18, 73, 61, 55, 52, 54, 51, 26, 75, 65, 43, 23, 62, 45, 19,  3,  3,
       30, 81, 65,  0, 33, 59, 71,  9, 43, 42, 46, 51, 75, 46, 35, 63])

In [80]:
arrr.min()   # returns the minimum vallue of element

0

In [82]:
arrr.max()   # returns the maximum vallue of element

95

In [85]:
arrr.argmax()  # returns the index position of the maximum value element

6

In [84]:
arrr.argmin() #return the index position of minimum value element

37

# 7.Shape 

In [87]:
arr.shape # It returns the length of array[]

(25,)

In [88]:
arrr.shape

(50,)

In [89]:
arr.reshape(25,1).shape

(25, 1)

In [90]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

# 8.dtype

In [91]:
arr.dtype

dtype('int32')

In [93]:
type(arr)

numpy.ndarray

# Broadcasting

In [95]:
arr1=np.arange(11)

In [96]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr1[1:5]

array([1, 2, 3, 4])

In [99]:
arr1[1:5]=1000

In [100]:
arr1

array([   0, 1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10])

In [101]:
arr1[1:5]

array([1000, 1000, 1000, 1000])

In [102]:
slice_of_arr=arr1[1:5]

In [103]:
slice_of_arr

array([1000, 1000, 1000, 1000])

In [104]:
slice_of_arr[:]=99

In [105]:
slice_of_arr  #you want to see the magik

array([99, 99, 99, 99])

In [106]:
arr1  #see magik here 
      #your original arry totally changed

array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

# Indexing a 2D Array

In [107]:
arr_2d=np.array(([1,2,3],[4,5,6],[7,8,9]))

In [108]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [113]:
arr_2d[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [114]:
arr_2d[2]

array([7, 8, 9])

In [118]:
arr_2d[1,2]

6

# Selection

In [123]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [127]:
bool_arr=arr>4

In [128]:
arr[bool_arr]

array([5, 6, 7, 8, 9])